#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
nohup ${OPENSHIFT_REPO_DIR}/github/github.py > ${OPENSHIFT_DIY_LOG_DIR}/github.log 2>&1 &
